// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.9;

error ZeroAddress();
error NotOperator();
error SameOperator();
error OperatorZeroAddress();
error Ended();
error NotStarted();
error NotEnded();
error RootNotSet();
error InvalidProof();
error InvalidHardCap();
error InvalidEndDate();
error InvalidStartDate();
error InvalidEthPrice();
error InvalidMinTokenBuy();
error InvalidMaxTokenBuy();
error InvalidProtocolFee();
error InvalidWhitelistProof();
error InvalidTokenHardCapIncrement();
error AmountTooLow();
error InvalidBuyAmount();
error AmountExceedsHardCap();
error AmountExceedsMaxTokenAmount();
error NotClaimable();
error NoPurchasedTokens();
error NoClaimableTokens();
error NoBalanceToWithdraw();
error EthereumTransferFailed();
error EthereumFeeTransferFailed();
